spring.data.mongodb.database=movies
spring.data.mongodb.uri=mongodb+srv://ajembachizoba_db_user:tBGZ1KUtF2EJgYF1@cluster0.f5hubxu.mongodb.net
mongodb+srv://emmanuelibegbu25_db_user:<dm9IqlGCIVHmEY8T>@cluster0.onzymzw.mongodb.net/?appName=Cluster0